; generated by Slic3r 1.2.9 on 2016-02-19 at 19:09:01
>
; external perimeters extrusion width = 0.10mm
; perimeters extrusion width = 0.11mm
; infill extrusion width = 0.11mm
; solid infill extrusion width = 0.11mm
; top infill extrusion width = 0.11mm
; support material extrusion width = 0.10mm

M107
M104 S200 ; set temperature

M109 S200 ; wait for temperature to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
;G1024 
;G1024 
;G1024 
;G1024 
G1 Z0.100 F14400.000
G1 X45 Y45 E2
G1 X135 Y135 E2
G1 X45 Y135 E2
G1 X135 Y45 E2

G Z0.2 F14440
